CXX=g++
LD=g++
CXXFLAGS=-Wall -pedantic -Wno-long-long -g -O0 -ggdb -std=gnu++11
LIBS=-lncurses
USERNAME=pesekja8
all: $(USERNAME) doc
compile: $(USERNAME)
$(USERNAME): src/main.o src/enviroment.o src/character.o src/brick.o src/walls.o src/exceptions.o src/bomb.o src/network.o
	$(LD) -o $(USERNAME) src/enviroment.o src/main.o src/character.o src/brick.o src/walls.o src/exceptions.o src/bomb.o src/network.o $(LIBS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
run:
	./$(USERNAME)
doc:
	doxygen src/Doxyfile

clean:
	rm -rf src/*.o $(USERNAME) doc


#automaticlly generated by g++ -MM *cpp
bomb.o: src/bomb.cpp src/bomb.h src/character.h src/brick.h src/walls.h
brick.o: src/brick.cpp src/brick.h
character.o: src/character.cpp src/character.h src/brick.h src/bomb.h \
 src/walls.h
enviroment.o: src/enviroment.cpp src/enviroment.h src/character.h \
 src/brick.h src/bomb.h src/walls.h src/exceptions.h
exceptions.o: src/exceptions.cpp src/exceptions.h
main.o: src/main.cpp src/enviroment.h src/character.h src/brick.h \
 src/bomb.h src/walls.h src/exceptions.h src/network.h
network.o: src/network.cpp src/network.h src/enviroment.h src/character.h \
 src/brick.h src/bomb.h src/walls.h src/exceptions.h
walls.o: src/walls.cpp src/walls.h src/brick.h
